spring:
  application:
    name: Solace-IBMMQ-Connector-OSS-SIT-1
  #boot:
  #  admin:
  #    client:
  #      url: http://
  cloud:
    stream:
      binders:
        # 1st solace binder in this example
        solace-oss-sit:
          type: solace
          environment:
            solace:
              java:
                host: tcps://oss-msg-sit.dsu.ocp.psa:55443
                msg-vpn: oss
                client-username: ${SECRET_MGMT_Q_USERNAME}
                client-password: ${SECRET_MGMT_Q_PASSWORD}
                connect-retries: 1
                connect-retries-per-host: 1
                api-properties:
                  SSL_TRUST_STORE: /app/external/classpath/truststores/truststore.jks
                  SSL_TRUST_STORE_FORMAT: jks
                  SSL_TRUST_STORE_PASSWORD: ${SECRET_TRUSTSTORE_PASS}
                  SSL_VALIDATE_CERTIFICATE: false
        general-mq:
          type: jms
          environment:
            ibm:
              mq:
                channel: SYSTEM.DEF.SVRCONN
                #user:
                #password:
                queue-manager: GENERAL.QUEUE.MANAGER
                conn-name: 10.115.68.112(1414)
        citos-ct3-mq:
          type: jms
          environment:
            ibm:
              mq:
                channel: SYSTEM.DEF.SVRCONN
                #user:
                #password:
                queue-manager: CITOS.CT3.QUEUE.MANAGER
                conn-name: 10.115.69.111(1414)
        test-mq:
          type: jms
          environment:
            ibm:
              mq:
                channel: SYSTEM.DEF.SVRCONN
                #user:
                #password:
                queue-manager: TEST.QUEUE.MANAGER
                conn-name: 10.115.4.56(1414)
        # Required for internal use
        undefined:
          type: undefined
      bindings:
        input-0:
          destination: tsid.test.fr.client.q
          binder: general-mq
        output-0:
          destination: oss.tss.temppass.tpass.trans.t
          binder: solace-oss-sit
        input-1:
          destination: oss.tss.temppass.fr.oss.tss.temppass.q
          binder: solace-oss-sit
        output-1:
          destination: oss.tss.temppass.tpass.trans.t
          binder: general-mq
        input-2:
          destination: citos.pmts.auto.arr.fr.citos.pmts.reply.ct3.q
          binder: solace-oss-sit
        output-2:
          destination: citos.pmts.auto.arr.fr.citos.pmts.reply.ct3.q
          binder: citos-ct3-mq
        input-3:
          destination: citos.pmts.tos.c.fr.citos.pmts.reply.r.ct3.q
          binder: citos-ct3-mq
        output-3:
          destination: psa/sg/oss/pmts/-/reply/ct3/v1/-/-/-/-
          binder: solace-oss-sit
        input-4:
          destination: infra-test-queue
          binder: solace-oss-sit
        output-4:
          destination: test.recv.t
          binder: test-mq
      solace:
        default:
          consumer:
            destination-type: queue
          producer:
            destination-type: topic
      jms:
        default:
          consumer:
            destination-type: queue
          producer:
            destination-type: topic
        bindings:
          #input-1:
          #consumer:
          #    destination-type: queue
          output-2:
            producer:
              destination-type: queue
solace:
  connector:
    workflows:
      0:
        enabled: false
      1:
        enabled: true
      2:
        enabled: true
      3:
        enabled: true
        transform-headers:
          expressions:
            solace_timeToLive: "headers.jms_expiration == null || headers.jms_expiration <= 0 ? 0L : headers.jms_expiration - headers.jms_timestamp"
      4:
        enabled: false
    management:
      leader-election:
        mode: active_standby
        fail-over:
          max-attempts: 5
          back-off-initial-interval: 1000
          back-off-max-interval: 10000
          back-off-multipler: 1.5
      queue: infra-conn-queue_ibm-connector_oss-1_mgmt
      session:
        host: tcps://oss-msg-sit.dsu.ocp.psa:55443
        msg-vpn: oss
        client-username: ${SECRET_MGMT_Q_USERNAME}
        client-password: ${SECRET_MGMT_Q_PASSWORD}
        api-properties:
          SSL_TRUST_STORE: /app/external/classpath/truststores/truststore.jks
          SSL_TRUST_STORE_FORMAT: jks
          SSL_TRUST_STORE_PASSWORD: ${SECRET_TRUSTSTORE_PASS}
            #              SSL_VALIDATE_CERTIFICATE: false
logging:
  level:
    root: INFO
    com.solace.connector.jms: DEBUG
    com.solace.connector.core: DEBUG
    com.solace.spring.cloud.stream.binder: INFO