// Package podmangen renders podman deployment artifacts for the Solace PubSub+
// Connector for IBM MQ: either a POSIX sh `podman run` script (mode=run) or one
// systemd .container quadlet unit per shard (mode=quadlet). It is pure: no
// os/exec, no filesystem, no globals, no network -- it only builds strings. The
// caller resolves credentials to an env-file path and stores/libs to host bind
// mounts before calling; exec safety is the runner's job, so this package emits
// the values it is given verbatim.
package podmangen

import (
	"strings"

	"github.com/solacecommunity/hafio-solace/connectors/ibmmq/solmq-conn/internal/spec"
)

// appYAMLTarget is the in-container path each shard's application.yml is
// bind-mounted to (read-only); podman cannot inline file content.
const appYAMLTarget = "/app/external/spring/config/application.yml"

// javaToolOptions is the JAVA_TOOL_OPTIONS value set when a shard uses MQ TLS,
// selecting the IBM cipher mappings the connector expects.
const javaToolOptions = "-Dcom.ibm.mq.cfg.useIBMCipherMappings=false"

// Instance is one connector shard (a folder with more than the per-instance
// workflow cap is sharded into several).
type Instance struct {
	Name        string // container name for this shard (already suffixed by caller if sharded)
	AppYAMLPath string // host path to this shard's application.yml on disk (bind-mounted)
	MQTLS       bool   // when true, add JAVA_TOOL_OPTIONS env for IBM cipher mappings
}

// Mount is one read-only bind mount (host path -> container path).
type Mount struct {
	Source string // host path
	Target string // absolute container path
}

// Input is everything the podman renderers need. The caller resolves creds to an
// env-file path and stores/libs to host bind mounts before calling.
type Input struct {
	Podman    *spec.Podman
	Instances []Instance // one or more shards; >=1
	EnvFile   string     // env-file path; "" when there are no credentials
	Stores    []Mount    // .jks bind mounts (read-only); nil/empty when none
	Libs      *Mount     // libs dir bind mount (read-only); nil when none
}

// Unit is one rendered quadlet file.
type Unit struct {
	Filename string // e.g. "solmq-connector.container"
	Content  string
}

// sw is a small line-oriented string builder (mirrors internal/deploy's builder).
type sw struct{ b strings.Builder }

func (w *sw) line(s string)  { w.b.WriteString(s); w.b.WriteByte('\n') }
func (w *sw) String() string { return w.b.String() }

// RenderRunScript returns a POSIX sh script that runs each instance via
// `podman run -d`. Each instance is one block; blocks are separated by a blank
// line. Within a block every line but the last ends with " \" and continuation
// lines are indented two spaces; the image is the last line with no backslash.
func RenderRunScript(in Input) string {
	p := in.Podman
	w := &sw{}
	w.line("#!/bin/sh")
	w.line("# Generated by solmq-conn -- podman run script for the Solace PubSub+ Connector for IBM MQ.")
	w.line("set -eu")
	w.line("")

	for bi, inst := range in.Instances {
		if bi > 0 {
			w.line("")
		}
		args := runArgs(in, p, inst)
		for i, arg := range args {
			prefix := ""
			if i > 0 {
				prefix = "  "
			}
			suffix := " \\"
			if i == len(args)-1 {
				suffix = ""
			}
			w.line(prefix + arg + suffix)
		}
	}
	return w.String()
}

// runArgs builds the ordered argv-style lines for one `podman run -d` block,
// from the leading `podman run -d` to the trailing image line.
func runArgs(in Input, p *spec.Podman, inst Instance) []string {
	args := []string{"podman run -d"}
	args = append(args, "--name "+inst.Name)
	if p.Restart != "" {
		args = append(args, "--restart "+p.Restart)
	}
	for _, port := range p.Ports {
		args = append(args, "-p "+port.String())
	}
	if p.Timezone != "" {
		args = append(args, "-e TZ="+p.Timezone)
	}
	if inst.MQTLS {
		args = append(args, "-e JAVA_TOOL_OPTIONS="+javaToolOptions)
	}
	if in.EnvFile != "" {
		args = append(args, "--env-file "+in.EnvFile)
	}
	args = append(args, "-v "+inst.AppYAMLPath+":"+appYAMLTarget+":ro")
	for _, m := range in.Stores {
		args = append(args, "-v "+m.Source+":"+m.Target+":ro")
	}
	if in.Libs != nil {
		args = append(args, "-v "+in.Libs.Source+":"+in.Libs.Target+":ro")
	}
	args = append(args, p.Image)
	return args
}

// RenderQuadlet returns one .container quadlet unit per instance; the filename is
// "<Name>.container". Sections are emitted in order [Unit], [Container],
// [Service], [Install], separated by blank lines. The [Service] section is
// omitted entirely when Restart is empty.
func RenderQuadlet(in Input) []Unit {
	p := in.Podman
	units := make([]Unit, 0, len(in.Instances))
	for _, inst := range in.Instances {
		w := &sw{}
		w.line("# Generated by solmq-conn -- podman quadlet unit for the Solace PubSub+ Connector for IBM MQ.")

		w.line("[Unit]")
		w.line("Description=Solace PubSub+ Connector for IBM MQ (" + inst.Name + ")")
		w.line("After=network-online.target")
		w.line("Wants=network-online.target")
		w.line("")

		w.line("[Container]")
		w.line("Image=" + p.Image)
		w.line("ContainerName=" + inst.Name)
		for _, port := range p.Ports {
			w.line("PublishPort=" + port.String())
		}
		if p.Timezone != "" {
			w.line("Environment=TZ=" + p.Timezone)
		}
		if inst.MQTLS {
			w.line("Environment=JAVA_TOOL_OPTIONS=" + javaToolOptions)
		}
		if in.EnvFile != "" {
			w.line("EnvironmentFile=" + in.EnvFile)
		}
		w.line("Volume=" + inst.AppYAMLPath + ":" + appYAMLTarget + ":ro")
		for _, m := range in.Stores {
			w.line("Volume=" + m.Source + ":" + m.Target + ":ro")
		}
		if in.Libs != nil {
			w.line("Volume=" + in.Libs.Source + ":" + in.Libs.Target + ":ro")
		}
		w.line("")

		if p.Restart != "" {
			w.line("[Service]")
			w.line("Restart=" + p.Restart)
			w.line("")
		}

		w.line("[Install]")
		w.line("WantedBy=default.target")

		units = append(units, Unit{Filename: inst.Name + ".container", Content: w.String()})
	}
	return units
}
