package podmangen

import (
	"strings"
	"testing"

	"github.com/solacecommunity/hafio-solace/connectors/ibmmq/solmq-conn/internal/spec"
)

const testImage = "solace/solace-pubsub-connector-ibmmq:2.13.0"

// fullInput is the representative single-instance case: creds + one store + libs
// + MQTLS, restart and timezone set.
func fullInput() Input {
	return Input{
		Podman: &spec.Podman{
			Command:  "podman",
			Mode:     spec.PodmanModeRun,
			Image:    testImage,
			Name:     "solmq-connector",
			Ports:    []spec.Port{{Host: 8090, Container: 8090}, {Host: 8080, Container: 8091}},
			Restart:  "unless-stopped",
			Timezone: "Asia/Singapore",
		},
		Instance: Instance{Name: "solmq-connector", AppYAMLPath: "./solmq-connector-application.yml", MQTLS: true},
		Secrets: []SecretRef{
			{StoreName: "solmq-connector-MQ_CONN_1_USER", Target: "MQ_CONN_1_USER"},
			{StoreName: "solmq-connector-MQ_CONN_1_PASSWORD", Target: "MQ_CONN_1_PASSWORD"},
		},
		Stores: []Mount{
			{Source: "/abs/certs/truststore.jks", Target: "/app/external/classpath/truststores/truststore.jks"},
		},
		Libs: &Mount{Source: "/abs/libs", Target: "/app/external/libs"},
	}
}

// minimalInput is the bare case: no creds/stores/libs, MQTLS false, empty
// timezone, empty restart. Only a single port remains.
func minimalInput() Input {
	return Input{
		Podman: &spec.Podman{
			Mode:  spec.PodmanModeRun,
			Image: testImage,
			Name:  "solmq-connector",
			Ports: []spec.Port{{Host: 8090, Container: 8090}},
		},
		Instance: Instance{Name: "solmq-connector", AppYAMLPath: "./solmq-connector-application.yml", MQTLS: false},
	}
}

func TestRenderRunScriptFull(t *testing.T) {
	want := `#!/bin/sh
# Generated by solmq-conn-util -- podman run script for the Solace PubSub+ Connector for IBM MQ.
set -eu

# Load credentials into podman's secret store. Values come from this
# script's environment -- export them first; nothing is stored here.
podman secret rm --ignore solmq-connector-MQ_CONN_1_USER >/dev/null
printf '%s' "${MQ_CONN_1_USER:?MQ_CONN_1_USER is not set}" | podman secret create solmq-connector-MQ_CONN_1_USER - >/dev/null
podman secret rm --ignore solmq-connector-MQ_CONN_1_PASSWORD >/dev/null
printf '%s' "${MQ_CONN_1_PASSWORD:?MQ_CONN_1_PASSWORD is not set}" | podman secret create solmq-connector-MQ_CONN_1_PASSWORD - >/dev/null

podman run -d \
  --name solmq-connector \
  --restart unless-stopped \
  -p 8090:8090 \
  -p 8080:8091 \
  -e TZ=Asia/Singapore \
  -e JAVA_TOOL_OPTIONS=-Dcom.ibm.mq.cfg.useIBMCipherMappings=false \
  --secret solmq-connector-MQ_CONN_1_USER,type=mount,target=MQ_CONN_1_USER \
  --secret solmq-connector-MQ_CONN_1_PASSWORD,type=mount,target=MQ_CONN_1_PASSWORD \
  -v ./solmq-connector-application.yml:/app/external/spring/config/application.yml:ro \
  -v /abs/certs/truststore.jks:/app/external/classpath/truststores/truststore.jks:ro \
  -v /abs/libs:/app/external/libs:ro \
  solace/solace-pubsub-connector-ibmmq:2.13.0
`
	if got := RenderRunScript(fullInput()); got != want {
		t.Errorf("RenderRunScript full mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestRenderRunScriptSecretPreamble asserts the secret-loading preamble in
// isolation: it must carry no credential value, only the stable name
// referenced via ${NAME:?...} -- the actual value comes from whoever runs the
// script, read from their own environment at that point.
func TestRenderRunScriptSecretPreamble(t *testing.T) {
	in := minimalInput()
	in.Secrets = []SecretRef{
		{StoreName: "solmq-connector-MQ_CONN_1_USER", Target: "MQ_CONN_1_USER"},
		{StoreName: "solmq-connector-MQ_CONN_1_PASSWORD", Target: "MQ_CONN_1_PASSWORD"},
	}
	got := RenderRunScript(in)

	wantPreamble := `# Load credentials into podman's secret store. Values come from this
# script's environment -- export them first; nothing is stored here.
podman secret rm --ignore solmq-connector-MQ_CONN_1_USER >/dev/null
printf '%s' "${MQ_CONN_1_USER:?MQ_CONN_1_USER is not set}" | podman secret create solmq-connector-MQ_CONN_1_USER - >/dev/null
podman secret rm --ignore solmq-connector-MQ_CONN_1_PASSWORD >/dev/null
printf '%s' "${MQ_CONN_1_PASSWORD:?MQ_CONN_1_PASSWORD is not set}" | podman secret create solmq-connector-MQ_CONN_1_PASSWORD - >/dev/null
`
	if !strings.Contains(got, wantPreamble) {
		t.Errorf("RenderRunScript preamble mismatch:\n--- got ---\n%s\n--- want substring ---\n%s", got, wantPreamble)
	}

	for _, s := range in.Secrets {
		ref := "${" + s.Target + ":?" + s.Target + " is not set}"
		if !strings.Contains(got, ref) {
			t.Errorf("RenderRunScript missing env reference %q in:\n%s", ref, got)
		}
	}
}

// TestRenderRunScriptNoSecretsOmitsPreamble asserts that when no secrets are
// given, no secret-store lines are emitted at all -- the preamble is entirely
// conditional on Input.Secrets, not always present with an empty body.
func TestRenderRunScriptNoSecretsOmitsPreamble(t *testing.T) {
	got := RenderRunScript(minimalInput())
	if strings.Contains(got, "podman secret") {
		t.Errorf("RenderRunScript with no secrets must omit secret-store lines, got:\n%s", got)
	}
}

func TestRenderRunScriptMinimal(t *testing.T) {
	want := `#!/bin/sh
# Generated by solmq-conn-util -- podman run script for the Solace PubSub+ Connector for IBM MQ.
set -eu

podman run -d \
  --name solmq-connector \
  -p 8090:8090 \
  -v ./solmq-connector-application.yml:/app/external/spring/config/application.yml:ro \
  solace/solace-pubsub-connector-ibmmq:2.13.0
`
	if got := RenderRunScript(minimalInput()); got != want {
		t.Errorf("RenderRunScript minimal mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestRenderQuadletFull(t *testing.T) {
	unit := RenderQuadlet(fullInput())
	if unit.Filename != "solmq-connector.container" {
		t.Errorf("filename = %q, want %q", unit.Filename, "solmq-connector.container")
	}
	want := `# Generated by solmq-conn-util -- podman quadlet unit for the Solace PubSub+ Connector for IBM MQ.
[Unit]
Description=Solace PubSub+ Connector for IBM MQ (solmq-connector)
After=network-online.target
Wants=network-online.target

[Container]
Image=solace/solace-pubsub-connector-ibmmq:2.13.0
ContainerName=solmq-connector
PublishPort=8090:8090
PublishPort=8080:8091
Environment=TZ=Asia/Singapore
Environment=JAVA_TOOL_OPTIONS=-Dcom.ibm.mq.cfg.useIBMCipherMappings=false
Secret=solmq-connector-MQ_CONN_1_USER,type=mount,target=MQ_CONN_1_USER
Secret=solmq-connector-MQ_CONN_1_PASSWORD,type=mount,target=MQ_CONN_1_PASSWORD
Volume=./solmq-connector-application.yml:/app/external/spring/config/application.yml:ro
Volume=/abs/certs/truststore.jks:/app/external/classpath/truststores/truststore.jks:ro
Volume=/abs/libs:/app/external/libs:ro

[Service]
Restart=unless-stopped

[Install]
WantedBy=default.target
`
	if unit.Content != want {
		t.Errorf("RenderQuadlet full mismatch:\n--- got ---\n%s\n--- want ---\n%s", unit.Content, want)
	}
}

func TestRenderQuadletMinimal(t *testing.T) {
	unit := RenderQuadlet(minimalInput())
	want := `# Generated by solmq-conn-util -- podman quadlet unit for the Solace PubSub+ Connector for IBM MQ.
[Unit]
Description=Solace PubSub+ Connector for IBM MQ (solmq-connector)
After=network-online.target
Wants=network-online.target

[Container]
Image=solace/solace-pubsub-connector-ibmmq:2.13.0
ContainerName=solmq-connector
PublishPort=8090:8090
Volume=./solmq-connector-application.yml:/app/external/spring/config/application.yml:ro

[Install]
WantedBy=default.target
`
	if unit.Content != want {
		t.Errorf("RenderQuadlet minimal mismatch:\n--- got ---\n%s\n--- want ---\n%s", unit.Content, want)
	}
}
