package podmangen

import (
	"strings"
	"testing"

	"github.com/solacecommunity/hafio-solace/connectors/ibmmq/solmq-conn/internal/logback"
	"github.com/solacecommunity/hafio-solace/connectors/ibmmq/solmq-conn/internal/spec"
	"github.com/solacecommunity/hafio-solace/connectors/ibmmq/solmq-conn/internal/statusscript"
)

const testImage = "solace/solace-pubsub-connector-ibmmq:2.13.0"

// fullInput is the representative single-instance case: creds + one store + libs
// + MQTLS, restart and timezone set.
func fullInput() Input {
	return Input{
		Podman: &spec.Podman{
			Command: "podman",
			Name:    "solmq-connector",
			Ports:   []spec.Port{{Host: 8090, Container: 8090}, {Host: 8080, Container: 8091}},
			Restart: "unless-stopped",
		},
		Instance: Instance{Name: "solmq-connector", Image: testImage, Timezone: "Asia/Singapore", AppYAMLSecret: "solmq-connector-application.yml", MQTLS: true, StatusScriptSecret: "solmq-connector-status-script", LeaderMode: spec.LeaderActiveActive},
		Secrets: []SecretRef{
			{StoreName: "solmq-connector-MQ_CONN_1_USER", Target: "MQ_CONN_1_USER"},
			{StoreName: "solmq-connector-MQ_CONN_1_PASSWORD", Target: "MQ_CONN_1_PASSWORD"},
		},
		Stores: []FileSecret{
			{StoreName: "solmq-connector-tls-truststore", Target: "/app/external/classpath/truststores/truststore.jks"},
		},
		Libs: &Mount{Source: "/abs/libs", Target: "/app/external/libs"},
	}
}

// minimalInput is the bare case: no creds/stores/libs, MQTLS false, empty
// timezone, empty restart. Only a single port remains.
func minimalInput() Input {
	return Input{
		Podman: &spec.Podman{
			Name:  "solmq-connector",
			Ports: []spec.Port{{Host: 8090, Container: 8090}},
		},
		Instance: Instance{Name: "solmq-connector", Image: testImage, AppYAMLSecret: "solmq-connector-application.yml", MQTLS: false, StatusScriptSecret: "solmq-connector-status-script", LeaderMode: ""},
	}
}

// TestRenderQuadletSecretsCarryNoValues asserts the unit references each
// credential by its stable store name only. The value itself lives in podman's
// secret store, placed there by deploy; a unit is a world-readable file in the
// quadlet directory, so a value appearing here would be a credential on disk.
func TestRenderQuadletSecretsCarryNoValues(t *testing.T) {
	in := minimalInput()
	in.Secrets = []SecretRef{
		{StoreName: "solmq-connector-MQ_CONN_1_USER", Target: "MQ_CONN_1_USER"},
		{StoreName: "solmq-connector-MQ_CONN_1_PASSWORD", Target: "MQ_CONN_1_PASSWORD"},
	}
	got := RenderQuadlet(in).Content

	for _, s := range in.Secrets {
		want := "Secret=" + s.StoreName + ",type=mount,target=" + spec.SecretsMountPath + "/" + s.Target
		if !strings.Contains(got, want) {
			t.Errorf("RenderQuadlet missing secret directive %q in:\n%s", want, got)
		}
	}
}

func TestRenderQuadletFull(t *testing.T) {
	unit := RenderQuadlet(fullInput())
	if unit.Filename != "solmq-connector.container" {
		t.Errorf("filename = %q, want %q", unit.Filename, "solmq-connector.container")
	}
	want := `# Generated by solmq-conn-util -- podman quadlet unit for the Solace PubSub+ Connector for IBM MQ.
[Unit]
Description=Solace PubSub+ Connector for IBM MQ (solmq-connector)
After=network-online.target
Wants=network-online.target

[Container]
Image=solace/solace-pubsub-connector-ibmmq:2.13.0
ContainerName=solmq-connector
Label=solace-connector/le-mode=active_active
Label=solace-connector/role=active
PublishPort=8090:8090
PublishPort=8080:8091
Environment=TZ=Asia/Singapore
Environment=JAVA_TOOL_OPTIONS=-Dcom.ibm.mq.cfg.useIBMCipherMappings=false
Secret=solmq-connector-MQ_CONN_1_USER,type=mount,target=/app/external/var/secrets/MQ_CONN_1_USER
Secret=solmq-connector-MQ_CONN_1_PASSWORD,type=mount,target=/app/external/var/secrets/MQ_CONN_1_PASSWORD
Secret=solmq-connector-application.yml,type=mount,target=/app/external/spring/config/application.yml
Secret=solmq-connector-tls-truststore,type=mount,target=/app/external/classpath/truststores/truststore.jks
Secret=solmq-connector-status-script,type=mount,target=/app/external/.status-script
Volume=/abs/libs:/app/external/libs:ro
HealthCmd=sh /app/external/.status-script --health
HealthInterval=30s
HealthTimeout=10s
HealthRetries=3
HealthStartPeriod=60s

[Service]
Restart=unless-stopped

[Install]
WantedBy=default.target
`
	if unit.Content != want {
		t.Errorf("RenderQuadlet full mismatch:\n--- got ---\n%s\n--- want ---\n%s", unit.Content, want)
	}
}

func TestRenderQuadletMinimal(t *testing.T) {
	unit := RenderQuadlet(minimalInput())
	want := `# Generated by solmq-conn-util -- podman quadlet unit for the Solace PubSub+ Connector for IBM MQ.
[Unit]
Description=Solace PubSub+ Connector for IBM MQ (solmq-connector)
After=network-online.target
Wants=network-online.target

[Container]
Image=solace/solace-pubsub-connector-ibmmq:2.13.0
ContainerName=solmq-connector
Label=solace-connector/le-mode=standalone
Label=solace-connector/role=active
PublishPort=8090:8090
Secret=solmq-connector-application.yml,type=mount,target=/app/external/spring/config/application.yml
Secret=solmq-connector-status-script,type=mount,target=/app/external/.status-script
HealthCmd=sh /app/external/.status-script --health
HealthInterval=30s
HealthTimeout=10s
HealthRetries=3
HealthStartPeriod=60s

[Install]
WantedBy=default.target
`
	if unit.Content != want {
		t.Errorf("RenderQuadlet minimal mismatch:\n--- got ---\n%s\n--- want ---\n%s", unit.Content, want)
	}
}

// TestLeaderLabelsPerMode asserts the mode label is always present and the
// role label is present only for standalone and active_active.
func TestLeaderLabelsPerMode(t *testing.T) {
	tests := []struct {
		name     string
		mode     string
		wantMode string
		wantRole bool
	}{
		{"empty defaults to standalone", "", spec.LeaderStandalone, true},
		{"standalone", spec.LeaderStandalone, spec.LeaderStandalone, true},
		{"active_active", spec.LeaderActiveActive, spec.LeaderActiveActive, true},
		{"active_standby", spec.LeaderActiveStby, spec.LeaderActiveStby, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			in := minimalInput()
			in.Instance.LeaderMode = tt.mode

			wantModeLine := "Label=" + spec.LabelModeKey + "=" + tt.wantMode
			wantRoleLine := "Label=" + spec.LabelRoleKey + "=" + spec.LabelRoleActive
			unit := RenderQuadlet(in)
			if !strings.Contains(unit.Content, wantModeLine) {
				t.Errorf("RenderQuadlet(%q) missing mode label %q, got:\n%s", tt.mode, wantModeLine, unit.Content)
			}
			if strings.Contains(unit.Content, wantRoleLine) != tt.wantRole {
				t.Errorf("RenderQuadlet(%q) role label present = %v, want %v, got:\n%s", tt.mode, strings.Contains(unit.Content, wantRoleLine), tt.wantRole, unit.Content)
			}
		})
	}
}

// TestQuadletMountsNothingFromTheHostButLibs pins the point of mounting every
// file from podman's secret store: with everything set -- credentials, a
// store, the status script, syslog and libs -- the libs directory is the one
// Volume= line, and every Secret= line mounts at an absolute target, since a
// bare one would land in podman's /run/secrets where nothing reads it.
func TestQuadletMountsNothingFromTheHostButLibs(t *testing.T) {
	in := fullInput()
	in.Syslog = &spec.Syslog{Host: "syslog.corp", Port: 514, Protocol: spec.SyslogUDP}
	in.Instance.LogbackSecret = "solmq-connector-logback-spring.xml"
	var volumes, secrets []string
	for _, line := range strings.Split(RenderQuadlet(in).Content, "\n") {
		switch {
		case strings.HasPrefix(line, "Volume="):
			volumes = append(volumes, line)
		case strings.HasPrefix(line, "Secret="):
			secrets = append(secrets, line)
			if !strings.Contains(line, ",type=mount,target=/") {
				t.Errorf("secret mount without an absolute target: %s", line)
			}
		}
	}
	if len(volumes) != 1 || volumes[0] != "Volume=/abs/libs:/app/external/libs:ro" {
		t.Errorf("the libs directory must be the only Volume=, got %q", volumes)
	}
	// Two credentials, application.yml, the truststore, the status script and
	// the logback config.
	if len(secrets) != 6 {
		t.Errorf("want 6 Secret= lines, got %d: %q", len(secrets), secrets)
	}
}

// TestStatusScriptMountOmittedWhenSecretEmpty asserts a caller that names no
// status script secret (a partial render) gets no mount for it, rather than a
// Secret= line with an empty name.
//
// It covers the healthcheck in the same breath: HealthCmd execs that same
// path, so a unit that mounts no script must declare no check either, or
// podman would report every such container unhealthy.
func TestStatusScriptMountOmittedWhenSecretEmpty(t *testing.T) {
	in := fullInput()
	in.Instance.StatusScriptSecret = ""

	unit := RenderQuadlet(in)
	if strings.Contains(unit.Content, statusTarget) {
		t.Errorf("RenderQuadlet with empty StatusScriptSecret must omit the status mount, got:\n%s", unit.Content)
	}
	if strings.Contains(unit.Content, "Health") {
		t.Errorf("RenderQuadlet with empty StatusScriptSecret must omit the healthcheck, got:\n%s", unit.Content)
	}
}

// TestHealthcheckRunsTheStatusScript covers the Health* keys. Without them
// podman populates no .State.Health and `status container` can only report
// n/a in the HEALTH column -- the defect these keys exist to fix.
//
// Every value is built from the statusscript constants, so the quadlet check,
// the compose healthcheck and the kubernetes readiness probe cannot drift.
func TestHealthcheckRunsTheStatusScript(t *testing.T) {
	unit := RenderQuadlet(fullInput())

	wantCmd := "HealthCmd=" + statusscript.HealthShell + " " + statusscript.ContainerPath + " " + statusscript.HealthArg + "\n"
	if !strings.Contains(unit.Content, wantCmd) {
		t.Errorf("HealthCmd missing:\nwant %q\ngot:\n%s", wantCmd, unit.Content)
	}
	for _, want := range []string{
		"HealthInterval=30s\n",
		"HealthTimeout=10s\n",
		"HealthRetries=3\n",
		"HealthStartPeriod=60s\n",
	} {
		if !strings.Contains(unit.Content, want) {
			t.Errorf("quadlet health key %q missing:\n%s", want, unit.Content)
		}
	}
	// HealthOnFailure is deliberately absent: podman defaults it to none, so
	// the check reports a verdict and never restarts or kills anything. Naming
	// it here means a future edit that adds one has to argue with this test.
	if strings.Contains(unit.Content, "HealthOnFailure") {
		t.Errorf("HealthOnFailure must stay unset -- the check reports, it does not act:\n%s", unit.Content)
	}
	// The keys belong to [Container], not [Service] or [Install]: quadlet only
	// translates them there.
	ctr := strings.Index(unit.Content, "[Container]")
	cmd := strings.Index(unit.Content, "HealthCmd=")
	next := strings.Index(unit.Content, "[Install]")
	if svc := strings.Index(unit.Content, "[Service]"); svc != -1 && svc < next {
		next = svc
	}
	if ctr == -1 || cmd < ctr || cmd > next {
		t.Errorf("health keys must sit inside [Container]:\n%s", unit.Content)
	}
}

// TestQuadletJavaOptionsEnvironment covers the java-options: block in the
// unit: both variables are set, the MQ TLS flag stays first in
// JAVA_TOOL_OPTIONS, and a value with spaces is quoted whole -- unquoted,
// systemd would split it into one assignment per option and the container
// would get only the first.
func TestQuadletJavaOptionsEnvironment(t *testing.T) {
	in := minimalInput()
	in.Instance.MQTLS = true
	in.Instance.JavaOptions = &spec.JavaOptions{Tool: "-Xms512m\n-Xmx1g", JDK: "-Duser.language=en"}
	unit := RenderQuadlet(in).Content
	for _, want := range []string{
		`Environment="JAVA_TOOL_OPTIONS=-Dcom.ibm.mq.cfg.useIBMCipherMappings=false -Xms512m -Xmx1g"` + "\n",
		// A single option has no space, so it keeps the unquoted form every
		// other Environment= line in the unit uses.
		"Environment=JDK_JAVA_OPTIONS=-Duser.language=en\n",
	} {
		if !strings.Contains(unit, want) {
			t.Errorf("unit missing %q:\n%s", want, unit)
		}
	}

	// Nothing set: neither variable appears, not even empty.
	plain := RenderQuadlet(minimalInput()).Content
	if strings.Contains(plain, "JAVA_TOOL_OPTIONS") || strings.Contains(plain, "JDK_JAVA_OPTIONS") {
		t.Errorf("no TLS and no java-options must set no JVM options variable:\n%s", plain)
	}
}

// TestSystemdEnvEscapes pins the rules systemdEnv exists for: '%' doubled so
// systemd does not expand it as a specifier (the %p of a JVM error-file path
// would otherwise become the unit's name), a value with a space quoted whole,
// and quotes and backslashes escaped inside those quotes.
func TestSystemdEnvEscapes(t *testing.T) {
	for _, c := range []struct{ value, want string }{
		{"-Xmx1g", "Environment=V=-Xmx1g"},
		{"-XX:ErrorFile=/tmp/hs_err_%p.log", "Environment=V=-XX:ErrorFile=/tmp/hs_err_%%p.log"},
		{"-Xms512m -Xmx1g", `Environment="V=-Xms512m -Xmx1g"`},
		{"-Dx=%t -Dy=z", `Environment="V=-Dx=%%t -Dy=z"`},
		{`-Dx="a"`, `Environment="V=-Dx=\"a\""`},
		{`-Dpath=C:\tmp`, `Environment="V=-Dpath=C:\\tmp"`},
	} {
		if got := systemdEnv("V", c.value); got != c.want {
			t.Errorf("systemdEnv(%q) = %s, want %s", c.value, got, c.want)
		}
	}
}

// syslogInput is minimalInput plus a syslog block and the secret the logback
// config is loaded into. podman cannot inline file content, so unlike compose
// the config reaches the container from podman's secret store.
func syslogInput() Input {
	in := minimalInput()
	in.Syslog = &spec.Syslog{Host: "syslog.corp", Port: 514, Protocol: spec.SyslogUDP}
	in.Instance.LogbackSecret = "solmq-connector-logback-spring.xml"
	return in
}

// TestQuadletSyslogMountsAndSetsEnv covers what the syslog hoist bought podman:
// before it, logging.syslog was a kubernetes-only key and a podman deployment got
// nothing at all.
func TestQuadletSyslogMountsAndSetsEnv(t *testing.T) {
	out := RenderQuadlet(syslogInput()).Content
	for _, want := range []string{
		"Secret=solmq-connector-logback-spring.xml,type=mount,target=" + logback.ContainerPath + "\n",
		"Environment=LOGGING_SYSLOG_APPNAME=solmq-connector",
		"Environment=LOGGING_SYSLOG_HOST=syslog.corp",
		"Environment=LOGGING_SYSLOG_PORT=514",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("quadlet unit is missing %q, got:\n%s", want, out)
		}
	}
}

// TestSyslogAbsentEmitsNoMountOrEnv is the negative: no block, no mount, no env.
func TestSyslogAbsentEmitsNoMountOrEnv(t *testing.T) {
	out := RenderQuadlet(minimalInput()).Content
	for _, no := range []string{"logback", "LOGGING_SYSLOG"} {
		if strings.Contains(out, no) {
			t.Errorf("quadlet unit should not mention %q without a syslog block, got:\n%s", no, out)
		}
	}
}
