package podmangen

import (
	"testing"

	"github.com/solacecommunity/hafio-solace/connectors/ibmmq/solmq-conn/internal/spec"
)

const testImage = "solace/solace-pubsub-connector-ibmmq:2.13.0"

// fullInput is the representative single-instance case: creds + one store + libs
// + MQTLS, restart and timezone set.
func fullInput() Input {
	return Input{
		Podman: &spec.Podman{
			Command:  "podman",
			Mode:     spec.PodmanModeRun,
			Image:    testImage,
			Name:     "solmq-connector",
			Ports:    []spec.Port{{Host: 8090, Container: 8090}, {Host: 8080, Container: 8091}},
			Restart:  "unless-stopped",
			Timezone: "Asia/Singapore",
		},
		Instances: []Instance{
			{Name: "solmq-connector", AppYAMLPath: "./solmq-connector-application.yml", MQTLS: true},
		},
		EnvFile: "solmq-connector.env",
		Stores: []Mount{
			{Source: "/abs/certs/truststore.jks", Target: "/app/external/classpath/truststores/truststore.jks"},
		},
		Libs: &Mount{Source: "/abs/libs", Target: "/app/external/libs"},
	}
}

// minimalInput is the bare case: no creds/stores/libs, MQTLS false, empty
// timezone, empty restart. Only a single port remains.
func minimalInput() Input {
	return Input{
		Podman: &spec.Podman{
			Mode:  spec.PodmanModeRun,
			Image: testImage,
			Name:  "solmq-connector",
			Ports: []spec.Port{{Host: 8090, Container: 8090}},
		},
		Instances: []Instance{
			{Name: "solmq-connector", AppYAMLPath: "./solmq-connector-application.yml", MQTLS: false},
		},
	}
}

func TestRenderRunScriptFull(t *testing.T) {
	want := `#!/bin/sh
# Generated by solmq-conn -- podman run script for the Solace PubSub+ Connector for IBM MQ.
set -eu

podman run -d \
  --name solmq-connector \
  --restart unless-stopped \
  -p 8090:8090 \
  -p 8080:8091 \
  -e TZ=Asia/Singapore \
  -e JAVA_TOOL_OPTIONS=-Dcom.ibm.mq.cfg.useIBMCipherMappings=false \
  --env-file solmq-connector.env \
  -v ./solmq-connector-application.yml:/app/external/spring/config/application.yml:ro \
  -v /abs/certs/truststore.jks:/app/external/classpath/truststores/truststore.jks:ro \
  -v /abs/libs:/app/external/libs:ro \
  solace/solace-pubsub-connector-ibmmq:2.13.0
`
	if got := RenderRunScript(fullInput()); got != want {
		t.Errorf("RenderRunScript full mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestRenderRunScriptMinimal(t *testing.T) {
	want := `#!/bin/sh
# Generated by solmq-conn -- podman run script for the Solace PubSub+ Connector for IBM MQ.
set -eu

podman run -d \
  --name solmq-connector \
  -p 8090:8090 \
  -v ./solmq-connector-application.yml:/app/external/spring/config/application.yml:ro \
  solace/solace-pubsub-connector-ibmmq:2.13.0
`
	if got := RenderRunScript(minimalInput()); got != want {
		t.Errorf("RenderRunScript minimal mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestRenderRunScriptMultiInstance(t *testing.T) {
	in := Input{
		Podman: &spec.Podman{
			Mode:    spec.PodmanModeRun,
			Image:   testImage,
			Name:    "solmq-connector",
			Ports:   []spec.Port{{Host: 8090, Container: 8090}},
			Restart: "unless-stopped",
		},
		Instances: []Instance{
			{Name: "solmq-connector-1", AppYAMLPath: "./a1.yml", MQTLS: false},
			{Name: "solmq-connector-2", AppYAMLPath: "./a2.yml", MQTLS: false},
		},
	}
	want := `#!/bin/sh
# Generated by solmq-conn -- podman run script for the Solace PubSub+ Connector for IBM MQ.
set -eu

podman run -d \
  --name solmq-connector-1 \
  --restart unless-stopped \
  -p 8090:8090 \
  -v ./a1.yml:/app/external/spring/config/application.yml:ro \
  solace/solace-pubsub-connector-ibmmq:2.13.0

podman run -d \
  --name solmq-connector-2 \
  --restart unless-stopped \
  -p 8090:8090 \
  -v ./a2.yml:/app/external/spring/config/application.yml:ro \
  solace/solace-pubsub-connector-ibmmq:2.13.0
`
	if got := RenderRunScript(in); got != want {
		t.Errorf("RenderRunScript multi mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestRenderQuadletFull(t *testing.T) {
	units := RenderQuadlet(fullInput())
	if len(units) != 1 {
		t.Fatalf("want 1 unit, got %d", len(units))
	}
	if units[0].Filename != "solmq-connector.container" {
		t.Errorf("filename = %q, want %q", units[0].Filename, "solmq-connector.container")
	}
	want := `# Generated by solmq-conn -- podman quadlet unit for the Solace PubSub+ Connector for IBM MQ.
[Unit]
Description=Solace PubSub+ Connector for IBM MQ (solmq-connector)
After=network-online.target
Wants=network-online.target

[Container]
Image=solace/solace-pubsub-connector-ibmmq:2.13.0
ContainerName=solmq-connector
PublishPort=8090:8090
PublishPort=8080:8091
Environment=TZ=Asia/Singapore
Environment=JAVA_TOOL_OPTIONS=-Dcom.ibm.mq.cfg.useIBMCipherMappings=false
EnvironmentFile=solmq-connector.env
Volume=./solmq-connector-application.yml:/app/external/spring/config/application.yml:ro
Volume=/abs/certs/truststore.jks:/app/external/classpath/truststores/truststore.jks:ro
Volume=/abs/libs:/app/external/libs:ro

[Service]
Restart=unless-stopped

[Install]
WantedBy=default.target
`
	if units[0].Content != want {
		t.Errorf("RenderQuadlet full mismatch:\n--- got ---\n%s\n--- want ---\n%s", units[0].Content, want)
	}
}

func TestRenderQuadletMinimal(t *testing.T) {
	units := RenderQuadlet(minimalInput())
	if len(units) != 1 {
		t.Fatalf("want 1 unit, got %d", len(units))
	}
	want := `# Generated by solmq-conn -- podman quadlet unit for the Solace PubSub+ Connector for IBM MQ.
[Unit]
Description=Solace PubSub+ Connector for IBM MQ (solmq-connector)
After=network-online.target
Wants=network-online.target

[Container]
Image=solace/solace-pubsub-connector-ibmmq:2.13.0
ContainerName=solmq-connector
PublishPort=8090:8090
Volume=./solmq-connector-application.yml:/app/external/spring/config/application.yml:ro

[Install]
WantedBy=default.target
`
	if units[0].Content != want {
		t.Errorf("RenderQuadlet minimal mismatch:\n--- got ---\n%s\n--- want ---\n%s", units[0].Content, want)
	}
}

func TestRenderQuadletMultiInstance(t *testing.T) {
	in := Input{
		Podman: &spec.Podman{
			Mode:    spec.PodmanModeQuadlet,
			Image:   testImage,
			Name:    "solmq-connector",
			Ports:   []spec.Port{{Host: 8090, Container: 8090}},
			Restart: "unless-stopped",
		},
		Instances: []Instance{
			{Name: "solmq-connector-1", AppYAMLPath: "./a1.yml", MQTLS: false},
			{Name: "solmq-connector-2", AppYAMLPath: "./a2.yml", MQTLS: false},
		},
	}
	units := RenderQuadlet(in)
	if len(units) != 2 {
		t.Fatalf("want 2 units, got %d", len(units))
	}
	if units[0].Filename != "solmq-connector-1.container" {
		t.Errorf("unit[0] filename = %q, want %q", units[0].Filename, "solmq-connector-1.container")
	}
	if units[1].Filename != "solmq-connector-2.container" {
		t.Errorf("unit[1] filename = %q, want %q", units[1].Filename, "solmq-connector-2.container")
	}
}
