// Package podmangen renders podman deployment artifacts for the Solace PubSub+
// Connector for IBM MQ: either a POSIX sh `podman run` script (mode=run) or a
// systemd .container quadlet unit (mode=quadlet). It is pure: no os/exec, no
// filesystem, no globals, no network -- it only builds strings. The caller
// resolves credentials to secret-store references and stores/libs to host bind
// mounts before calling; exec safety is the runner's job, so this package emits
// the values it is given verbatim.
package podmangen

import (
	"github.com/solacecommunity/hafio-solace/connectors/ibmmq/solmq-conn/internal/spec"
	"github.com/solacecommunity/hafio-solace/connectors/ibmmq/solmq-conn/internal/yamlwriter"
)

// appYAMLTarget is the in-container path the application.yml is bind-mounted to
// (read-only); podman cannot inline file content.
const appYAMLTarget = "/app/external/spring/config/application.yml"

// javaToolOptions is the JAVA_TOOL_OPTIONS value set when the connector uses MQ TLS,
// selecting the IBM cipher mappings the connector expects.
const javaToolOptions = "-Dcom.ibm.mq.cfg.useIBMCipherMappings=false"

// Instance is the connector: its container name and on-disk config path.
type Instance struct {
	Name        string // container name
	AppYAMLPath string // host path to the application.yml on disk (bind-mounted)
	MQTLS       bool   // when true, add JAVA_TOOL_OPTIONS env for IBM cipher mappings
}

// Mount is one read-only bind mount (host path -> container path).
type Mount struct {
	Source string // host path
	Target string // absolute container path
}

// SecretRef is one credential from podman's secret store, mounted into the
// container. StoreName is how podman knows it (namespaced by container name,
// since the store is shared across every project on the host); Target is the
// file name it appears under in /run/secrets, which is the stable name the
// connector's config references.
type SecretRef struct {
	StoreName string
	Target    string
}

// Input is everything the podman renderers need. The caller resolves stores/libs
// to host bind mounts and credentials to secret-store references before calling.
type Input struct {
	Podman   *spec.Podman
	Instance Instance
	Secrets  []SecretRef // podman secret store entries to mount; nil/empty when none
	Stores   []Mount     // .jks bind mounts (read-only); nil/empty when none
	Libs     *Mount      // libs dir bind mount (read-only); nil when none
}

// Unit is one rendered quadlet file.
type Unit struct {
	Filename string // e.g. "solmq-connector.container"
	Content  string
}

// sw is the shared line writer; podman's lines are never nested, so every
// call below passes indent 0 to Line.
type sw = yamlwriter.Writer

// RenderRunScript returns a POSIX sh script that runs each instance via
// `podman run -d`. Each instance is one block; blocks are separated by a blank
// line. Within a block every line but the last ends with " \" and continuation
// lines are indented two spaces; the image is the last line with no backslash.
func RenderRunScript(in Input) string {
	p := in.Podman
	w := &sw{}
	w.Line(0, "#!/bin/sh")
	w.Line(0, "# Generated by solmq-conn-util -- podman run script for the Solace PubSub+ Connector for IBM MQ.")
	w.Line(0, "set -eu")
	w.Line(0, "")
	renderSecretPreamble(w, in.Secrets)

	args := runArgs(in, p, in.Instance)
	for i, arg := range args {
		prefix := ""
		if i > 0 {
			prefix = "  "
		}
		suffix := " \\"
		if i == len(args)-1 {
			suffix = ""
		}
		w.Line(0, prefix+arg+suffix)
	}
	return w.String()
}

// renderSecretPreamble emits the lines that load each credential into podman's
// secret store before the containers start.
//
// The script carries no credential values -- each is read from the environment
// of whoever runs the script, and `:?` makes an unset one abort with a named
// error rather than storing an empty secret. `rm --ignore` first makes a re-run
// idempotent on podman 4.5, which has no `create --replace`. Values reach podman
// on stdin, never on a command line where `ps` would expose them.
func renderSecretPreamble(w *sw, secrets []SecretRef) {
	if len(secrets) == 0 {
		return
	}
	w.Line(0, "# Load credentials into podman's secret store. Values come from this")
	w.Line(0, "# script's environment -- export them first; nothing is stored here.")
	for _, s := range secrets {
		w.Line(0, "podman secret rm --ignore "+s.StoreName+" >/dev/null")
		w.Line(0, "printf '%s' \"${"+s.Target+":?"+s.Target+" is not set}\" | podman secret create "+s.StoreName+" - >/dev/null")
	}
	w.Line(0, "")
}

// runArgs builds the ordered argv-style lines for the `podman run -d` block,
// from the leading `podman run -d` to the trailing image line.
func runArgs(in Input, p *spec.Podman, inst Instance) []string {
	args := []string{"podman run -d"}
	args = append(args, "--name "+inst.Name)
	if p.Restart != "" {
		args = append(args, "--restart "+p.Restart)
	}
	for _, port := range p.Ports {
		args = append(args, "-p "+port.String())
	}
	if p.Timezone != "" {
		args = append(args, "-e TZ="+p.Timezone)
	}
	if inst.MQTLS {
		args = append(args, "-e JAVA_TOOL_OPTIONS="+javaToolOptions)
	}
	for _, s := range in.Secrets {
		args = append(args, "--secret "+s.StoreName+",type=mount,target="+s.Target)
	}
	args = append(args, "-v "+inst.AppYAMLPath+":"+appYAMLTarget+":ro")
	for _, m := range in.Stores {
		args = append(args, "-v "+m.Source+":"+m.Target+":ro")
	}
	if in.Libs != nil {
		args = append(args, "-v "+in.Libs.Source+":"+in.Libs.Target+":ro")
	}
	args = append(args, p.Image)
	return args
}

// RenderQuadlet returns the .container quadlet unit; the filename is
// "<Name>.container". Sections are emitted in order [Unit], [Container],
// [Service], [Install], separated by blank lines. The [Service] section is
// omitted entirely when Restart is empty.
func RenderQuadlet(in Input) Unit {
	p := in.Podman
	inst := in.Instance
	w := &sw{}
	w.Line(0, "# Generated by solmq-conn-util -- podman quadlet unit for the Solace PubSub+ Connector for IBM MQ.")

	w.Line(0, "[Unit]")
	w.Line(0, "Description=Solace PubSub+ Connector for IBM MQ ("+inst.Name+")")
	w.Line(0, "After=network-online.target")
	w.Line(0, "Wants=network-online.target")
	w.Line(0, "")

	w.Line(0, "[Container]")
	w.Line(0, "Image="+p.Image)
	w.Line(0, "ContainerName="+inst.Name)
	for _, port := range p.Ports {
		w.Line(0, "PublishPort="+port.String())
	}
	if p.Timezone != "" {
		w.Line(0, "Environment=TZ="+p.Timezone)
	}
	if inst.MQTLS {
		w.Line(0, "Environment=JAVA_TOOL_OPTIONS="+javaToolOptions)
	}
	for _, s := range in.Secrets {
		w.Line(0, "Secret="+s.StoreName+",type=mount,target="+s.Target)
	}
	w.Line(0, "Volume="+inst.AppYAMLPath+":"+appYAMLTarget+":ro")
	for _, m := range in.Stores {
		w.Line(0, "Volume="+m.Source+":"+m.Target+":ro")
	}
	if in.Libs != nil {
		w.Line(0, "Volume="+in.Libs.Source+":"+in.Libs.Target+":ro")
	}
	w.Line(0, "")

	if p.Restart != "" {
		w.Line(0, "[Service]")
		w.Line(0, "Restart="+p.Restart)
		w.Line(0, "")
	}

	w.Line(0, "[Install]")
	w.Line(0, "WantedBy=default.target")

	return Unit{Filename: inst.Name + ".container", Content: w.String()}
}
