// Package statusscript renders the POSIX status script that runs inside the
// connector container. It is a pure renderer: no os/exec, no filesystem, no
// network, no globals -- it only builds and returns a string. The script it
// produces targets the connector image's busybox userland (Alpine's sh, sed,
// wget, tr, base64, head, cat -- no curl, no jq, no bash), so every construct
// below is deliberately POSIX/busybox-safe rather than bash- or
// GNU-coreutils-flavored.
package statusscript

import (
	"strconv"
	"strings"
)

// Filename is the script's name inside the container.
const Filename = "status"

// ContainerDir is the directory the script is written to inside the
// container -- the same libs mount the connector's IBM MQ jars use.
const ContainerDir = "/app/external/libs"

// ContainerPath is the script's full path inside the container.
const ContainerPath = ContainerDir + "/" + Filename

// ConfigDir is where this tool mounts the connector's application.yml, and is
// also what the image's own entrypoint passes as
// spring.config.additional-location, so it heads the script's search order.
const ConfigDir = "/app/external/spring/config"

// ConfigPath is the application.yml this tool mounts. The script reads the
// management account's password back from the config it finds at run time, so
// it never carries a credential of its own.
const ConfigPath = ConfigDir + "/application.yml"

// header is the constant part of the script up to (but not including) the
// PORT= / USER_NAME= assignments Render fills in. It is built from
// ContainerPath rather than a repeated literal so the exec examples can never
// drift from the path callers actually mount the script at.
const header = `#!/bin/sh
# Generated by solmq-conn-util -- reports this connector instance's
# leader-election mode and state plus per-workflow state, by querying the
# instance's own Spring actuator endpoints from inside the container.
#
# Run it with:
#   kubectl exec <pod> -- sh ` + ContainerPath + `
#   docker exec <container> sh ` + ContainerPath + `
#   podman exec <container> sh ` + ContainerPath + `
#
# Always exits 0. The report goes to stdout, anything that went wrong goes to
# stderr, and neither is encoded in the exit status: an exec wrapper should be
# able to treat a non-zero exit as "could not reach or run this instance"
# without a standby instance or a misconfigured endpoint looking like that.
# Read the "leader-election state:" line, not $?, to tell active from standby.
#
# set -u catches a typo in a variable name; set -e is deliberately NOT used,
# since a failing command must still reach the end and report on stderr. The
# EXIT trap keeps the 0 contract even if set -u aborts on an unguarded name.
set -u
trap 'exit 0' EXIT

`

// body is everything after the PORT= / USER_NAME= assignments: fully
// constant, so it is built once from ConfigDir rather than a repeated
// literal.
const body = `BASE="http://127.0.0.1:$PORT/actuator"
CONFIG_NAME=${SPRING_CONFIG_NAME:-application}

# Emits every readable application config, highest Spring precedence first: an
# explicit spring.config.location, then an additional-location, then the
# directory this image's entrypoint passes as an additional-location, then
# Spring's working-directory defaults. Spring would drop the defaults entirely
# once a location is set explicitly; they stay here as a fallback because the
# aim is to find whichever file actually carries the account and the exposure
# list, and the explicit location is searched first either way. classpath:
# entries live inside the jar, so nothing here can read them and they are
# skipped. A location ending in / is a directory to look for the config name
# in; anything else Spring treats as a file path, so this does too. Globs are
# left unquoted for the shell to expand, which means a location containing a
# space is unsupported -- as it is in the image's own defaults.
config_files() {
  IFS=','
  set -- ${SPRING_CONFIG_LOCATION:-} ${SPRING_CONFIG_ADDITIONAL_LOCATION:-}
  unset IFS
  for loc in "$@" ` + ConfigDir + `/ ` + ConfigDir + `/*/ ./ ./config/ ./config/*/; do
    [ -n "$loc" ] || continue
    loc=${loc#optional:}
    case "$loc" in
      classpath:*) continue ;;
    esac
    loc=${loc#file:}
    case "$loc" in
      */)
        for pattern in "$loc$CONFIG_NAME.yml" "$loc$CONFIG_NAME.yaml"; do
          for candidate in $pattern; do
            if [ -f "$candidate" ]; then
              echo "$candidate"
            fi
          done
        done
        ;;
      *)
        for candidate in $loc; do
          if [ -f "$candidate" ]; then
            echo "$candidate"
          fi
        done
        ;;
    esac
  done
  return 0
}

CONFIGS=$(config_files)
CONFIG_LIST=$(echo $CONFIGS)

# Runs one sed program against each config in precedence order and returns the
# first value found. Spring lets a configuration be split across files, and
# merging property sources is well beyond a shell script, so first hit wins.
from_configs() {
  for cfg in $CONFIGS; do
    value=$(sed -n "$1" "$cfg" | head -n 1)
    if [ -n "$value" ]; then
      printf %s "$value"
      return 0
    fi
  done
  return 0
}

# Membership test for one of Spring's comma-separated exposure lists. Both
# sides are delimited by commas so a longer entry that merely contains the
# name (leaderelection2) cannot match, and "*" counts as exposing everything.
has_entry() {
  entries=$(printf %s "$1" | tr -d '[:space:]')
  case ",$entries," in
    *",$2,"*) return 0 ;;
    *",*,"*) return 0 ;;
  esac
  return 1
}

# An endpoint that is not exposed answers 404, which by the time it reaches
# wget below is indistinguishable from a wrong port or a rejected credential.
# Checking the config first turns that dead end into one actionable error. An
# absent include list is a failure too, not an unknown: Spring then exposes
# health alone.
if [ -n "$CONFIGS" ]; then
  # Scoping the first lookup under exposure keeps an unrelated include key from
  # being mistaken for it. A hand-written config may inline the mapping instead,
  # so fall back to any include value and strip a trailing flow-style brace.
  EXPOSURE=$(from_configs '/^[[:space:]]*exposure:[[:space:]]*$/,$ {s/^[[:space:]]*include:[[:space:]]*//p;}')
  if [ -z "$EXPOSURE" ]; then
    EXPOSURE=$(from_configs 's/.*include:[[:space:]]*//p')
  fi
  EXPOSURE=$(printf %s "$EXPOSURE" | sed -e 's/}*$//' -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
  if ! has_entry "$EXPOSURE" leaderelection; then
    echo "status: leaderelection is not exposed by this instance -- management.endpoints.web.exposure.include is '${EXPOSURE:-unset, so only health is exposed}' in $CONFIG_LIST. Add leaderelection to that list, or regenerate and redeploy the config with solmq-conn-util, which always includes it." >&2
    exit 0
  fi
  if ! has_entry "$EXPOSURE" workflows; then
    echo "status: workflows is not in management.endpoints.web.exposure.include in $CONFIG_LIST, so per-workflow state is missing from this report" >&2
  fi
else
  echo "status: found no application config ($CONFIG_NAME.yml or $CONFIG_NAME.yaml) in SPRING_CONFIG_LOCATION, SPRING_CONFIG_ADDITIONAL_LOCATION, ` + ConfigDir + `/, ./ or ./config/, so actuator exposure and the management account could not be checked before querying" >&2
fi

# The account password is read back from the same config the connector reads,
# so the two always agree with no second copy to rotate. A ${...} value means
# the config routes the password through the secrets model, so follow it to the
# file configtree feeds Spring.
PASS=$(from_configs "/^[[:space:]]*-[[:space:]]*name:[[:space:]]*$USER_MATCH[[:space:]]*$/{n;s/^[[:space:]]*password:[[:space:]]*//p;}")
PASS=$(printf %s "$PASS" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
case "$PASS" in
  '${'*'}')
    SECRET_NAME=$(printf %s "$PASS" | sed -e 's/^\${//' -e 's/}$//')
    if [ -f "/run/secrets/$SECRET_NAME" ]; then
      PASS=$(cat "/run/secrets/$SECRET_NAME")
    else
      PASS=""
    fi
    ;;
esac

# No account in the config means management security is disabled, so the
# endpoints answer unauthenticated requests.
get() {
  if [ -n "$PASS" ]; then
    wget -qO- --header="Authorization: Basic $(printf %s:%s "$USER_NAME" "$PASS" | base64 | tr -d '\n')" "$1" 2>/dev/null
  else
    wget -qO- "$1" 2>/dev/null
  fi
}

LE=$(get "$BASE/leaderelection") || LE=""
if [ -z "$LE" ]; then
  echo "status: no answer from $BASE/leaderelection -- check the connector is up, that its actuator listens on port $PORT, and that the $USER_NAME account in ${CONFIG_LIST:-the application config} is valid" >&2
  exit 0
fi
MODE=$(printf %s "$LE" | sed -n 's/.*"type"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
STATE=$(printf %s "$LE" | sed -n 's/.*"state"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
echo "leader-election mode: ${MODE:-unknown}"
echo "leader-election state: ${STATE:-unknown}"

WF=$(get "$BASE/workflows") || WF=""
if [ -z "$WF" ]; then
  echo "status: no answer from $BASE/workflows -- check that workflows is in management.endpoints.web.exposure.include" >&2
else
  # Best-effort parsing with no jq in the busybox userland: split the
  # workflows JSON array on '{' and pull "id"/"state" out of each resulting
  # chunk with sed. This assumes a flat id/state shape per element and would
  # need reworking if the actuator response ever nests braces inside one.
  printf %s "$WF" | tr '{' '\n' | while IFS= read -r chunk; do
    id=$(printf %s "$chunk" | sed -n 's/.*"id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
    [ -n "$id" ] || continue
    st=$(printf %s "$chunk" | sed -n 's/.*"state"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
    echo "workflow $id: ${st:-unknown}"
  done
fi

# active and standby are both normal answers already printed above; only a
# value this script does not recognize is worth a word on stderr.
case "$STATE" in
  active | standby) ;;
  *)
    echo "status: unrecognized leader-election state '${STATE:-}' in the actuator response" >&2
    ;;
esac

exit 0
`

// breMeta are the characters that carry meaning in a POSIX basic regular
// expression, plus the '/' that delimits the sed address the account name is
// spliced into. A name is validated at the CLI boundary
// (validate.SafeActuatorUser) as well; escaping here is the sanitize-at-use
// half of that pair, so a name can never reshape the sed program even if it
// reaches this package by another route.
const breMeta = `\/.[]^$*`

// breEscape backslash-escapes every breMeta character in s.
func breEscape(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r < 0x80 && strings.ContainsRune(breMeta, r) {
			b.WriteByte('\\')
		}
		b.WriteRune(r)
	}
	return b.String()
}

// Render returns the status script text (trailing newline included). mgmtPort
// is the actuator's management port and user is the management account name
// the script authenticates as. The account name is emitted twice: verbatim for
// the Authorization header, and regex-escaped for the sed address that finds
// the account in the config. The escaped copy is single-quoted because it can
// carry backslashes the shell would otherwise strip.
func Render(mgmtPort int, user string) string {
	return header +
		"PORT=" + strconv.Itoa(mgmtPort) + "\n" +
		"USER_NAME=" + user + "\n" +
		"USER_MATCH='" + breEscape(user) + "'\n" +
		body
}
